# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shodan_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Whole_body = QtWidgets.QTabWidget(self.centralwidget)
        self.Whole_body.setGeometry(QtCore.QRect(10, 0, 541, 451))
        self.Whole_body.setStyleSheet("font: 9pt \"仿宋\";")
        self.Whole_body.setObjectName("Whole_body")
        self.grammar_tab = QtWidgets.QWidget()
        self.grammar_tab.setObjectName("grammar_tab")
        self.grammar_explaination = QtWidgets.QTextBrowser(self.grammar_tab)
        self.grammar_explaination.setGeometry(QtCore.QRect(10, 10, 511, 401))
        self.grammar_explaination.setStyleSheet("font: 9pt \"方正清刻本悦宋简体\";")
        self.grammar_explaination.setObjectName("grammar_explaination")
        self.Whole_body.addTab(self.grammar_tab, "")
        self.shodan_tab = QtWidgets.QWidget()
        self.shodan_tab.setObjectName("shodan_tab")
        self.search_button = QtWidgets.QPushButton(self.shodan_tab)
        self.search_button.setGeometry(QtCore.QRect(440, 40, 75, 23))
        self.search_button.setObjectName("search_button")
        self.shodan_search_label = QtWidgets.QLabel(self.shodan_tab)
        self.shodan_search_label.setGeometry(QtCore.QRect(30, 10, 111, 21))
        self.shodan_search_label.setObjectName("shodan_search_label")
        self.search_in = QtWidgets.QLineEdit(self.shodan_tab)
        self.search_in.setGeometry(QtCore.QRect(30, 40, 371, 21))
        self.search_in.setObjectName("search_in")
        self.save_button = QtWidgets.QPushButton(self.shodan_tab)
        self.save_button.setGeometry(QtCore.QRect(440, 70, 75, 23))
        self.save_button.setStyleSheet("font: 8pt \"仿宋\";")
        self.save_button.setObjectName("save_button")
        self.result_out = QtWidgets.QTableWidget(self.shodan_tab)
        self.result_out.setGeometry(QtCore.QRect(30, 100, 391, 311))
        self.result_out.setStyleSheet("QTableWidget::item::selected\n"
"{\n"
"    background:red;\n"
"}\n"
"")
        self.result_out.setObjectName("result_out")
        self.result_out.setColumnCount(4)
        self.result_out.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.result_out.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_out.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_out.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_out.setHorizontalHeaderItem(3, item)
        self.result_out.horizontalHeader().setDefaultSectionSize(100)
        self.result_label = QtWidgets.QLabel(self.shodan_tab)
        self.result_label.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.result_label.setObjectName("result_label")
        self.count_label = QtWidgets.QLabel(self.shodan_tab)
        self.count_label.setGeometry(QtCore.QRect(100, 70, 121, 16))
        self.count_label.setText("")
        self.count_label.setObjectName("count_label")
        self.log_out = QtWidgets.QTextBrowser(self.shodan_tab)
        self.log_out.setGeometry(QtCore.QRect(430, 160, 91, 251))
        self.log_out.setObjectName("log_out")
        self.clear_results_button = QtWidgets.QPushButton(self.shodan_tab)
        self.clear_results_button.setGeometry(QtCore.QRect(440, 100, 75, 23))
        self.clear_results_button.setStyleSheet("font: 8pt \"仿宋\";")
        self.clear_results_button.setObjectName("clear_results_button")
        self.clear_log_button = QtWidgets.QPushButton(self.shodan_tab)
        self.clear_log_button.setGeometry(QtCore.QRect(440, 130, 75, 23))
        self.clear_log_button.setObjectName("clear_log_button")
        self.search_page = QtWidgets.QLineEdit(self.shodan_tab)
        self.search_page.setGeometry(QtCore.QRect(350, 70, 51, 21))
        self.search_page.setObjectName("search_page")
        self.label = QtWidgets.QLabel(self.shodan_tab)
        self.label.setGeometry(QtCore.QRect(300, 70, 61, 21))
        self.label.setObjectName("label")
        self.Whole_body.addTab(self.shodan_tab, "")
        self.config_tab = QtWidgets.QWidget()
        self.config_tab.setObjectName("config_tab")
        self.config_label = QtWidgets.QLabel(self.config_tab)
        self.config_label.setGeometry(QtCore.QRect(30, 30, 141, 31))
        self.config_label.setObjectName("config_label")
        self.save_api_button = QtWidgets.QPushButton(self.config_tab)
        self.save_api_button.setGeometry(QtCore.QRect(120, 110, 75, 23))
        self.save_api_button.setObjectName("save_api_button")
        self.change_api_button = QtWidgets.QPushButton(self.config_tab)
        self.change_api_button.setGeometry(QtCore.QRect(340, 110, 75, 23))
        self.change_api_button.setObjectName("change_api_button")
        self.api_in = QtWidgets.QLineEdit(self.config_tab)
        self.api_in.setGeometry(QtCore.QRect(30, 70, 481, 21))
        self.api_in.setObjectName("api_in")
        self.Whole_body.addTab(self.config_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Whole_body.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "My shodan"))
        self.grammar_explaination.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'方正清刻本悦宋简体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">city:城市名称           城市的名称            city:&quot;Beijing&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">country:国家或者地区代码       国家的简称              country:&quot;CN&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">geo:经纬度           经纬度            geo:&quot;46.9481, 7.4474</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">hostname:主机名       主机名或者域名        hostname:&quot;baidu.com&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">ip:IP地址           IP地址            ip:&quot;11.11.11.11&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">isp:ISP供应商           ISP供应商            isp:&quot;China Telecom&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">org:组织或者公司       组织或者公司        org:&quot;baidu&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">os:操作系统           操作系统            os:&quot;Windows 7 or 8&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">port:端口号           端口号            port:80</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">net:CIDR格式的IP地址       CIDR格式的IP地址        net:&quot;190.30.40.0/24&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">version:软件版本号       软件版本            version:&quot;4.4.2&quot;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">http.server:服务类型       http请求返回中server的类型  http:server:apache</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">http.status:请求状态码       http请求返回响应码的状态    http.status:200</span></p></body></html>"))
        self.Whole_body.setTabText(self.Whole_body.indexOf(self.grammar_tab), _translate("MainWindow", "grammar"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.shodan_search_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">shodan search</span></p></body></html>"))
        self.save_button.setText(_translate("MainWindow", "Save result"))
        item = self.result_out.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP"))
        item = self.result_out.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Port"))
        item = self.result_out.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Domain"))
        item = self.result_out.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Country"))
        self.result_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">results:</span></p></body></html>"))
        self.clear_results_button.setText(_translate("MainWindow", "Clear result"))
        self.clear_log_button.setText(_translate("MainWindow", "Clear log"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">page:</span></p></body></html>"))
        self.Whole_body.setTabText(self.Whole_body.indexOf(self.shodan_tab), _translate("MainWindow", "shodan"))
        self.config_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">shodan config</span></p></body></html>"))
        self.save_api_button.setText(_translate("MainWindow", "Save"))
        self.change_api_button.setText(_translate("MainWindow", "Change"))
        self.Whole_body.setTabText(self.Whole_body.indexOf(self.config_tab), _translate("MainWindow", "config"))
